---
title: "New York Times 2020 Global Playlist"
author: "Slide Deck Created By Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, lucy, lucy-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}

options(htmltools.dir.version = FALSE)

xaringanExtra::use_tile_view()

xaringanExtra::use_share_again()

xaringanExtra::use_animate_css()

```

# How To Navigate

* Use the <span style="font-size:100px">&#8678;</span> and <span style="font-size:100px">&#8680;</span> keys to move through the presentation.
* Press *o* for *panel overview*.

```{r, echo=FALSE}

library(readxl)

playlist <- read_excel("NewYorkTimes2020GlobalPlaylist.xlsx")

```

```{r, echo=FALSE, results='asis'}

for (i in 1:10){
  
  cat(paste0("---\n", # new slide
             "class: animated slideInRight \n",
             "# ", # header
             playlist$song[i],
             "\n",
             "### by ",
             playlist$group[i],
             "\n",
             playlist$EmbedCode[i],
             "\n"))
  
}

```





