---
title: "Gender Inequality Index and Human Development Index"
description: |
  Data visualization.
author:
  - name: Andy Grogan-Kaylor 
    url: https://agrogan1.github.io/
    affiliation: University of Michigan
    affiliation_url: https://umich.edu/
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r}

library(readr) # to read CSV

library(dplyr) # data wrangling

library(tidyr) # tidy data

GII <- read_csv("GII_HDR2020_040722.csv") 

GII <- GII %>%
  select(iso3, country, gii_1995,
         gii_2000, 
         gii_2005, 
         gii_2010, 
         gii_2011, 
         gii_2012, 
         gii_2013,
         gii_2014, 
         gii_2015, 
         gii_2016, 
         gii_2017, 
         gii_2018, 
         gii_2019) %>% 
  pivot_longer(cols = starts_with("gii"),
    names_to = "year",
    names_prefix = "gii_",
    values_to = "GII",
    values_drop_na = TRUE)

HDI <- read_csv("HDI_HDR2020_040722.csv")

```









