---
title: "Country Level Bans on Corporal Punishment"
author:
  - name: Andy Grogan-Kaylor 
    url: https://agrogan1.github.io/
    affiliation: University of Michigan
    affiliation_url: https://www.umich.edu
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
  html_document: 
    highlight: haddock
    toc: yes
  bookdown::gitbook:
    highlight: haddock
    split_by: none
  pdf_document:
    toc: yes
mainfont: Tw Cen MT
always_allow_html: yes
---

```{r global_options, echo=FALSE}

knitr::opts_chunk$set(echo=FALSE, 
                      warning=FALSE, 
                      message=FALSE)

```

```{css, echo=FALSE}

d-article blockquote {
  color: black;
  border-left: 2px solid #FFCB05; 
  padding: 0.5em 10px;
}
.panelset {  
  color: #9A3324;
}
  
```

```{r call_libraries, eval = TRUE}

library(readr) # get data

library(foreign) # read and write other formats

library(maps) # basic mapping
# 
# library(maptools) # additional map tools
# 
# library(mapdata) # map data

library(countrycode) # code country names

# library(leaflet) # web maps

library(ggplot2) # nice graphs

library(ggthemes) # nice themes for ggplot2

library(ggrepel) # distance between ggplot labels

library(dplyr) # data wrangling

library(DT) # nifty data table

library(plotly) # interactive plots

library(fontawesome) # Font Awesome icons

library(xaringanExtra)

xaringanExtra::use_panelset()

```

```{r get_data, eval = TRUE}

mydata <- read_csv("CPBans.csv") # read data

save(mydata, file = "CPBans.RData") # save to R

write.dta(mydata, "CPBans.dta") # write to Stata

# make new data file of ALL Countries

AllCountries <- read_csv("AllCountries.csv") # read data

CPBans_w_AllCountries <- merge(mydata, 
                               AllCountries, 
                               by = "country_code",
                               all = TRUE) # merge


CPBans_w_AllCountries$continent <- 
  countrycode(CPBans_w_AllCountries$country_code, 
              origin = 'iso3c',
              destination = 'continent') 

save(CPBans_w_AllCountries, 
     file = "CPBans_w_AllCountries.RData") # save to R

write.dta(CPBans_w_AllCountries, 
          "CPBans_w_AllCountries.dta") # write to Stata

```

# Background 

**`r max(mydata$total.number.of.bans)`** countries have instituted country wide bans upon the use of corporal punishment with children.  The most recent country to institute a ban is **`r mydata$country[1]`**.

Information on countries that have banned corporal punishment available from  [endcorporalpunishment.org](http://endcorporalpunishment.org/)

# Visualizations

::::: {.panelset}

::: {.panel}
[Interactive Globe]{.panel-name}

```{r make_globe, eval = TRUE}

plot_geo(mydata) %>% 
  add_trace(locations = ~country_code, 
            color = ~year.of.prohibition,
            z = ~year.of.prohibition, 
            text = ~paste(country, 
                          "<br>year of prohibition:", 
                          year.of.prohibition),
            marker = list(size = 10)) %>%
  layout(title = "Countries With Bans on Corporal Punishment of Children", 
         geo = list(showland = FALSE,
                    showcountries = TRUE,
                    projection = list(type = 'orthographic',
                                      rotation = list(lon = -30,
                                                      lat = 10,
                                                      roll = 0)
                                      ))) %>%
  colorbar(title = 'year of prohibition') 

```

:::

::: {.panel}
[Map]{.panel-name}

```{r make_map}

plot_geo(mydata) %>%
  add_trace(locations = ~country_code, 
            color = ~year.of.prohibition,
            z = ~year.of.prohibition,
            # hoverinfo = "text",
            text = ~paste(country, 
                          "<br>year of prohibition:", 
                          year.of.prohibition)) %>%
  layout(title = "Countries With Bans on Corporal Punishment of Children",
         width = 1000,
         height = 500,
         geo = list(showland = FALSE,
                    showcountries = TRUE,
                    projection = list(type = 'mollweide'))) %>%
  colorbar(title = 'year of prohibition')

```

:::

::: {.panel}
[Motion Chart]{.panel-name}

```{r make_motion_chart_data, eval = TRUE, echo = FALSE}

# create data with repeated observations for animation

mydata$number.repetitions <- 
  max(mydata$year.of.prohibition) + 
  1 - 
  mydata$year.of.prohibition

mydata2 <- data.frame(rep(mydata$country, 
                          mydata$number.repetitions),
                      rep(mydata$year.of.prohibition, 
                          mydata$number.repetitions),
                      rep(mydata$total.number.of.bans, 
                          mydata$number.repetitions))


names(mydata2)[1] <- "country"

names(mydata2)[2] <- "year.of.prohibition"

names(mydata2)[3] <- "number_bans"

mydata2 <- mydata2 %>% 
  group_by(country) %>% 
  mutate(id = n() - row_number()) %>%
  mutate(year = year.of.prohibition + id)

mydata2$country_iso <- countrycode(mydata2$country, 
                                 'country.name', 
                                 'iso3c')

```

```{r plotly_motion_chart, fig.height = 8, eval = TRUE, echo = FALSE}

# motion chart

mydata2 %>% 
  arrange(year, number_bans) %>% 
  plot_ly(x = ~year.of.prohibition, 
        y = ~number_bans,
        ids = ~country,
        frame = ~year, 
        color = ~year.of.prohibition, 
        type = 'scatter',
        mode = 'markers',
        text = ~country,
        textfont = list(color = toRGB("red")),
        textposition = 'middle right',
        marker = list(size = 10),
        showlegend = FALSE) %>%
  hide_colorbar() %>%
  layout(title = 'Country Level Bans on Corporal Punishment', 
         xaxis = list(title = "year", 
                      range = c(1975, 2025)),
         yaxis = list(title = "total number of bans")) 

```

:::

::: {.panel}
[Data Table]{.panel-name}

```{r make_data_table}

mynewdata <- subset(mydata, 
                    select = c(total.number.of.bans, 
                               country, 
                               year.of.prohibition))

datatable(mynewdata, 
          rownames = FALSE,
          # filter = 'top',
          caption = 'Countries With Bans on Corporal Punishment of Children',
          colnames = c('Number' = 1, 
                       'Country' = 2, 
                       'Year of Prohibition' = 3), 
          extensions = 'Buttons', 
          options = list(
            dom = 'Bfrtip',
            buttons = c('copy', 
                        'csv', 
                        'excel', 
                        'pdf', 
                        'print'))
          )

```

:::

::: {.panel}
[Graph]{.panel-name}

```{r make_graph, eval = TRUE, fig.height=6}

p1 <- ggplot(mydata, 
             aes(x = year.of.prohibition, 
                 y = total.number.of.bans)) + 
  geom_line(stat = "smooth", 
            method = "loess",
            color = "grey",
            span = 0.5,
            size = 3,
            alpha = .25) +
  geom_point(aes(color = total.number.of.bans),
             # color = "blue", 
             size = 1) +
  geom_text(aes(x = year.of.prohibition - .25 ,
                label = country),
            hjust = 1, 
            size = 2) +
  ggtitle("Total Number of Corporal Punishment Bans by Year") +
  xlim(1975, 
       max(mydata$year.of.prohibition)) +
  xlab("year") + 
  ylab("total number of bans") +
  theme_minimal() +
  scale_color_viridis_c()

p1

```

:::

::: {.panel}
[Interactive Graph]{.panel-name}

```{r make_interactive_graph, fig.height=8}

plot_ly(data = mydata, 
        x = ~year.of.prohibition, 
        y = ~total.number.of.bans,
        color = ~year.of.prohibition, 
        type = 'scatter',
        mode = 'marker',
        marker = list(size = 5),
        text = ~paste(country, 
                      '<br>', 
                      'year of ban:',
                      year.of.prohibition)) %>%
  add_annotations(x = mydata$year.of.prohibition,
                  y = mydata$total.number.of.bans,
                  text = mydata$country,
                  font = list(size = 8), 
                  showarrow = FALSE, 
                  xanchor = 'right') %>%
  layout(title = 'Country Level Bans on Corporal Punishment', 
         xaxis = list(title = "year"),
         yaxis = list(title = "total number of bans")) %>% 
  rangeslider()

```

:::

:::::





