---
title: "Meta-Analysis of Research on Corporal Punishment"
author: "Andy Grogan-Kaylor" 
date: "today"
format: 
  html:
    theme: cosmo
    toc: true
    number-sections: true
---

```{r}
#| column: page
#| fig-height: 4
#| echo: false
#| message: false

library(readxl)

CP_Meta_Summary_Results <- read_excel("data/CP Meta Summary Results.xlsx")

library(ggplot2)

library(plotly)

p1 <- ggplot(CP_Meta_Summary_Results,
             aes(x = reorder(Outcome, d),
                 y = d,
                 label = Outcome,
                 fill = d)) + 
  geom_bar(stat = "identity") +
  scale_fill_viridis_c() +
  coord_flip() +
  labs(title= "Effect Sizes of Physical Punishment",
       x = "Outcome",
       y = "Cohen's d Effect Size",
       caption = "Gershoff and Grogan-Kaylor, 2016") +
  theme(legend.position = "none",
        title = element_text(size = rel(.5)),
        axis.text = element_text(size = rel(.75)))

ggplotly(p1, tooltip = c("fill", "label"))

```

**Gershoff, E. T., & Grogan-Kaylor, A. (2016). Spanking and Child Outcomes: Old Controversies and New Meta-Analyses. Journal of Family Psychology. 30(4), 453-469. [http://dx.doi.org/10.1037/fam0000191](http://dx.doi.org/10.1037/fam0000191) [[PubMed Full Text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7992110/)]**

> This article received a [considerable amount of media attention](media-mentions-CP-meta.html).

Whether spanking is helpful or harmful to children continues to be the source of considerable debate among both researchers and the public. This article addresses 2 persistent issues, namely whether effect sizes for spanking are distinct from those for physical abuse, and whether effect sizes for spanking are robust to study design differences. Meta-analyses focused specifically on spanking were conducted on a total of 111 unique effect sizes representing 160,927 children. Thirteen of 17 mean effect sizes were significantly different from zero and all indicated a link between spanking and increased risk for detrimental child outcomes. Effect sizes did not substantially differ between spanking and physical abuse or by study design characteristics.
