---
title: "Research on Corporal Punishment"
description: |
  Research Articles
author:
  - name: Andy Grogan-Kaylor 
    url: https://agrogan1.github.io/
    affiliation: University of Michigan
    affiliation_url: https://umich.edu/
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

> I have authored, and collaborated on, a number of studies of corporal punishment.  In my research, I have consistently found that parental use of corporal punishment is associated with undesirable increases in outcomes like antisocial behavior, as well as anxiety and depression among children.  These findings are robust--and consistent across many different groups of parents and families--despite the fact that I have used statistical models which control for a number of possible alternative explanations.

# Articles:

**Ward, K. P., Lee, S. J., Pace, G. T., Grogan-Kaylor, A., &amp; Ma, J. (In Press). Attachment style and the association of spanking and child externalizing behavior. *Academic Pediatrics*.**

**Objective:** To examine whether the longitudinal associations between maternal spanking and child externalizing behavior are moderated by attachment
style.

**Methods:**  This study used data from the Fragile Families and Child Wellbeing Study (n = 2211), a large cohort sample of low-income urban families. Multiple-group autoregressive cross-lagged models examined the associations between maternal spanking and child externalizing behavior when children were
ages 1, 3, and 5. Moderation of attachment style was examined using structural invariance testing.

**Results:** For children with an insecure parent-child attachment style, spanking at age 1 was associated with externalizing behavior at age 3. However, for children with a secure parent-child attachment style, the association between maternal spanking at age 1 and child externalizing behavior
at age 3 was absent. Attachment style did not moderate the association between maternal spanking at age 3 and externalizing behavior at age 5, suggesting that spanking at age 3 is associated with deleterious outcomes at age 5, regardless
of attachment style.

**Conclusions:** Results suggest that, even in the context of a secure attachment style, spanking is associated with adverse outcomes in early childhood. Findings support the American Academy of Pediatrics 2018 policy statement, which encourages parents to avoid spanking when disciplining children. Results suggest that children, regardless of attachment style, may
benefit from policies and services that promote non-violent forms of discipline.

**Ward, K. P., Lee, S. J., Limb, G., Grogan-Kaylor, A. (In Press). Physical punishment and child externalizing behavior: Comparing American Indian, White, and African American children. *Journal of Interpersonal Violence*.**

The current study examined the associations of maternal spanking and child wellbeing for American Indian children. Analyses examined if, compared to White and African American children, spanking of American Indian children was associated with adverse child outcomes. Using a community-based sample of 3,632 children (1,183 White, 2,183 African American, 266 American Indian), multiple-group autoregressive cross-lagged models examined the association between maternal spanking and child externalizing behavior across the first five years of life. Rates of spanking for American Indian and White children were similar at all three time points (age 1, age 3, and age 5). The observed associations between spanking and child externalizing behavior for American Indian children were small but statistically significant and consistent with those the associations reported in prior studies of White and African American children. Results suggest that the positive association between spanking and externalizing behavior among American Indian children was not distinguishable from the associations found among White and African American children. Results of this study can be interpreted in light of the recent American Academy of Pediatrics statement that encourages pediatricians to counsel parents against the use of physical punishment. Similar to White and African American families, American Indian children may benefit from reducing or eliminating the use of physical punishment. 

**Cuartas, J., Grogan-Kaylor, A., Ma, J., Castillo, B. (In Press). Civil Conflict, Domestic Violence, and Poverty as Predictors of Corporal Punishment in Colombia, *Child Abuse and Neglect.* **


**Background:** With lingering effects from more than 50 years of war, young children in Colombia are exposed to multiple risk factors such as poverty, civil conflict, and domestic violence. In addition to these environmental stressors, public and legal support for corporal punishment remains high, which is shown by the high prevalence of young children exposed to corporal punishment in Colombia.

**Objective:** The purpose of this study is to identify individual, family, and municipality-level predictors of corporal punishment (i.e., hitting with objects and spanking) in Colombia in order to inform prevention and intervention strategies.

**Participants and Setting:** We use information gathered in 2015 from a representative sample of 11,759 mothers of children younger than five in Colombia. 

**Methods:** We employed multi-level models to account for the
clustering of families in 217 municipalities. 

**Results:** Results show that mothers’ prior exposure to corporal punishment by their own parents, attitudes towards domestic violence, municipality homicide rates and presence of armed groups, household poverty and poverty of the municipality predicted mothers’ hitting their young children with an object. However, family and municipality poverty had a negative association with mothers’ use of spanking.

**Conclusions:** These findings suggest that both family and neighborhood level factors have simultaneous associations with parents’ use of corporal punishment. Given the accumulating
evidence concerning the adverse effects of corporal
punishment on child well-being and development, legislative efforts aimed at reducing and ultimately banning physical punishment are warranted.

**Grogan-Kaylor, A., Ma, J., Lee, S., Castillo, B., Ward, K., Klein, S. (2018). Using Bayesian analysis to examine associations between spanking and child externalizing behavior across race and ethnic groups. *Child Abuse and Neglect*. 86, 257-266. [https://doi.org/10.1016/j.chiabu.2018.10.009](https://doi.org/10.1016/j.chiabu.2018.10.009)**

While corporal punishment is widely understood to have undesirable associations with children's behavior problems, there remains controversy as to whether such effects are consistent across different racial or ethnic groups. We employed a Bayesian regression analysis, which allows for the estimation of both similarities and differences across groups, to study whether there are differences in the relationship of corporal punishment and children’s behavior problems using a diverse, urban sample of U.S. families (n = 2,653). There is some moderation of the relationship between corporal punishment and child behavior by race or ethnicity. However, corporal punishment is associated with increases in behavior problems for all children. Thus, our findings add evidence from a new analytical lens that corporal punishment is consistently linked to increased externalizing behavior across African American, White, or Hispanic children, even after earlier externalizing behavior is controlled for. Our findings suggest that corporal punishment has detrimental consequences for all children and that all parents, regardless of their racial or ethnic background, should be advised to use alternatives to corporal punishment.

**Grogan-Kaylor, A., Burlaka, V., Ma, J., Lee, S., Castillo, B., Churakova, I. (2018). Predictors of Parental Use of Corporal Punishment Use in Ukraine, *Children and Youth Services Review*, 88, 66–73. [https://doi.org/10.1016/j.childyouth.2018.03.003](https://doi.org/10.1016/j.childyouth.2018.03.003)**

Despite a great deal of evidence that corporal punishment is harmful, corporal punishment is still very prevalent worldwide. We examine predictors of different types of corporal punishment among Ukrainian mothers in 12 communities across Ukraine. Findings suggest that maternal spirituality, maternal coping styles, family communication, and some demographic characteristics are predictive of mothers' use of corporal punishment.

**Highlights**

* Physical punishment is prevalent in Ukraine.
* Both individual level and macro level factors are associated with use of physical punishment.
* Interventions to reduce use of physical punishment should focus on both individual and community level factors.

**Grogan-Kaylor, A.C., Stein, S.F., Galano, M.M., Graham-Bermann, S.A. (In Press). Contributions to parenting under stress for women exposed to intimate partner violence. *Partner Abuse*.**

One in four women experience intimate partner violence (IPV) in their lifetime. Most of these women are mothers, raising young children, and parenting them under stressful conditions. This study examined a variety of parenting practices, and evaluated the contribution of child and mother demographic variables, the level of violence experienced by the mother, as well as mothers’ mental health, to the parenting practices of 172 women exposed to IPV from diverse ethno-racial groups. Results indicate socioeconomic variables make little contribution to variance in parenting practices, be they positive or negative. Yet younger child age, maternal depression and traumatic stress contribute to variation in negative parenting in families with IPV. Implications for future study and clinical work are discussed.

**Pace, G., Lee, S., Grogan-Kaylor, A. (2019). Spanking and young children's socioemotional development in low- and middle-income countries, *Child Abuse and Neglect*, 88, 84-95.**

<mark>**Open Access:**  [https://doi.org/10.1016/j.chiabu.2018.11.003](https://doi.org/10.1016/j.chiabu.2018.11.003)</mark>

Spanking is one of the most common forms of child discipline used by parents around the world. Research on children in high-income countries has shown that parental spanking is associated with adverse child outcomes, yet less is known about how spanking is related to child well-being in low- and middle-income countries. This study uses data from 215,885 children in 62 countries, which includes children from nearly one-third of the world’s countries, from the fourth and fifth rounds of UNICEF’s Multiple Indicator Cluster Surveys (MICS) to examine the relationship between spanking and child well-being. In this large international sample, 43% of 3- and 4-year-old children were spanked, or resided in a household where another child was spanked, in the past month. Results from multilevel models show that reports of spanking of children in the household were associated with lower scores on a 3-item socioemotional development index among 3- and 4-year-old children. Country-level results from the multilevel model showed 59 countries (95%) had a negative relationship between spanking and socioemotional development and 3 countries (5%) had a null relationship. Spanking was not associated with higher socioemotional development for children in any country. While the cross-sectional association between spanking and socioemotional development is small, findings suggest that spanking is consistently harmful for children on a more global scale than was previously known.

**Ma, J., Grogan-Kaylor, A., Klein, S. (2018). Neighborhood Collective Efficacy, Parental Spanking, and Subsequent Risk of Child Maltreatment, *Child Abuse and Neglect*, 80, 90-98. [https://doi.org/10.1016/j.chiabu.2018.03.019](https://doi.org/10.1016/j.chiabu.2018.03.019)**

Children exposed to negative neighborhood conditions and parental spanking are at higher risk of experiencing maltreatment. We conducted prospective analyses of secondary data to determine the effects of neighborhood collective efficacy and parental spanking on household Child Protective Services (CPS) involvement, and whether spanking mediates the relationship between neighborhood collective efficacy and CPS involvement. The sample (*N* = 2,267) was drawn from the Fragile Families and Child Wellbeing Study (FFCWS), a stratified random sample of 4,789 births between 1998 to 2000 in 20 large U.S. cities. Logistic regression models were employed to test the effects of neighborhood collective efficacy and spanking at child age 3 on mother’s report of CPS contact during the subsequent two years. The product-of-coefficient approach was used to test the mediation hypothesis. One aspect of neighborhood collective efficacy (i.e., Social Cohesion/Trust) is associated with lower odds of CPS involvement (OR = .80, 95% CI 0.670–0.951) after controlling for Informal Social Control, parental spanking, and the covariates. Parental spanking predicts increased odds of CPS involvement during the next two years (OR = 1.38, 95% CI 1.001–1.898), net of neighborhood collective efficacy and the covariates. The mediation hypothesis is not supported. Promoting both cohesive and trusting relationships between neighbors and non-physical discipline practices is likely to reduce the incidence of household CPS involvement.

**Ma, J., Grogan-Kaylor, A., Lee, S. (2018). Associations of neighborhood disorganization and maternal spanking with children's aggression: A fixed-effects regression analysis. *Child Abuse and Neglect*, 76, 106-116. [https://doi.org/10.1016/j.chiabu.2017.10.013](https://doi.org/10.1016/j.chiabu.2017.10.013)**

This study employed fixed effects regression that controls for selection bias, omitted variables bias, and all time-invariant aspects of parent and child characteristics to examine the simultaneous associations between neighborhood disorganization, maternal spanking, and aggressive behavior in early childhood using data from the Fragile Families and Child Wellbeing Study (FFCWS). Analysis was based on 2,472 children and their mothers who participated in Wave 3 (2001-2003; child age 3) and Wave 4 (2003-2006; child age 5) of the FFCWS. Results indicated that higher rates of neighborhood crime and violence predicted higher levels of child aggression. Maternal spanking in the past year, whether frequent or infrequent, was also associated with increases in aggressive behavior. This study contributes statistically rigorous evidence that exposure to violence in the neighborhood as well as the family context are predictors of child aggression. We conclude with a discussion for the need for multilevel prevention and intervention approaches that target both community and parenting factors.

**Grogan-Kaylor, A., Ma, J., Graham-Bermann, S.A. (2018). The Case Against Physical Punishment. *Current Opinion in Psychology*. 19, 22–27. [http://dx.doi.org/10.1016/j.copsyc.2017.03.022](http://dx.doi.org/10.1016/j.copsyc.2017.03.022)**

We review the literature on parental physical punishment of children, and lay out the foundations of a case against the use of physical punishment as a form of discipline. We consider the empirical research on physical punishment finding that physical punishment is associated with a number of undesirable outcomes for children and adolescents. We payspecial attention to questions of: parent effects versus child effects; whether parental use of physical punishment is moderated by family, neighborhood, or cultural context, and whether physical punishment can be considered to be partof a continuum of family violence. We close with some recommendations for positive parenting policies and practices.

**Merrick, M. T., Ports, K. A., Ford, D. C., Afifi, T. O., Gershoff, E. T., &amp; Grogan-Kaylor, A. (2017). Unpacking the impact of adverse childhood experiences on adult mental health. *Child Abuse &amp; Neglect*, 69, 10–19. [https://doi.org/10.1016/j.chiabu.2017.03.016](https://doi.org/10.1016/j.chiabu.2017.03.016)**

Exposure to childhood adversity has an impact on adult mental health, increasing the risk for depression and suicide. Associations between Adverse Childhood Experiences (ACEs) and several adult mental and behavioral health outcomes are well documented in the literature, establishing the need for prevention. The current study analyzes the relationship between an expanded ACE score that includes being spanked as a child and adult mental health outcomes by examining each ACE separately to determine the contribution of each ACE. Data were drawn from Wave II of the CDC-Kaiser ACE Study, consisting of 7,465 adult members of Kaiser Permanente in southern California. Dichotomous variables corresponding to each of the 11 ACE categories were created, with ACE score ranging from 0 to 11 corresponding to the total number of ACEs experienced. Multiple logistic regression modeling was used to examine the relationship between ACEs and adult mental health outcomes adjusting for sociodemographic covariates. Results indicated a graded dose-response relationship between the expanded ACE score and the likelihood of moderate to heavy drinking, drug use, depressed affect, and suicide attempts in adulthood. In the adjusted models, being spanked as a child was significantly associated with all self-reported mental health outcomes. Over 80% of the sample reported exposure to at least one ACE, signifying the potential to capture experiences not previously considered by traditional ACE indices. The findings highlight the importance of examining both cumulative ACE scores and individual ACEs on adult health outcomes to better understand key risk and protective factors for future prevention efforts.

**Afifi, T., Ford, D., Gershoff, E. T., Merrick, M., Grogan-Kaylor, A., Ports, K. A., MacMillan, H., Holden, G.W., Taylor, C.A., Lee, S.J., Bennett, R.P. (2017). Spanking and adult mental health impairment: The case for the designation of spanking as an adverse childhood experience. *Child Abuse and Neglect*, [http://dx.doi.org/10.1016/j.chiabu.2017.01.014](http://dx.doi.org/10.1016/j.chiabu.2017.01.014)**

Adverse Childhood Experiences (ACEs) such as child abuse are related to poor health outcomes. Spanking has indicated a similar association with health outcomes, but to date has not been considered an ACE. Physical and emotional abuse have been shown in previous research to correlate highly and may be similar in nature to spanking. To determine if spanking should be considered an ACE, this study aimed to examine 1): the grouping of spanking with physical and emotional abuse; and 2) if spanking has similar associations with poor adult health problems and accounts for additional model variance. Adult mental health problems included depressive affect, suicide attempts, moderate to heavy drinking, and street drug use. Data were from the CDC-Kaiser ACE study (N = 8316, response rate = 65%). Spanking loaded on the same factor as the physical and emotional abuse items. Additionally, spanking was associated with increased odds of suicide attempts (Adjusted Odds Ratios (AOR) = 1.37; 95% CI = 1.02 to1.86), moderate to heavy drinking (AOR) = 1.23; 95% CI = 1.07 to 1.41), and the use of street drugs (AOR) = 1.32; 95% CI = 1.4 to 1.52) in adulthood over and above experiencing physical and emotional abuse. This indicates spanking accounts for additional model variance and improves our understanding of these outcomes. Thus, spanking is empirically similar to physical and emotional abuse and including spanking with abuse adds to our understanding of these mental health problems. Spanking should also be considered an ACE and addressed in efforts to prevent violence.

**Ma, J., & Grogan-Kaylor, A. (2017). Longitudinal associations of neighborhood collective efficacy and maternal corporal punishment with behavior problems in early childhood. *Developmental Psychology*, 53(6), 1027–1041. [https://doi.org/10.1037/dev0000308](https://doi.org/10.1037/dev0000308)**

Neighborhood and parenting influences on early behavioral outcomes are strongly dependent upon a child’s stage of development. However, little research has jointly considered the longitudinal associations of neighborhood and parenting processes with early behavioral outcomes. To address this limitation, this study explores the associations of neighborhood collective efficacy and maternal corporal punishment with the longitudinal patterns of early externalizing and internalizing behavior problems. The study sample consisted of 3,705 families from a nationally representative cohort study of urban families. Longitudinal multilevel models examined the associations of collective efficacy and corporal punishment with behavior problems at age 3, as well as with patterns of behavior problems between the ages 3 to 5. Interactions between the main predictors and child age tested whether neighborhood and parent relationships with child behavior varied over time. Mediation analysis examined whether neighborhood influences on child behavior were mediated by parenting. The models controlled for a comprehensive set of possible confounders at the child, parent, and neighborhood levels. Results indicate that both maternal corporal punishment and low neighborhood collective efficacy were significantly associated with increased behavior problems. The significant interaction between collective efficacy and child age with internalizing problems suggests that neighborhood influences on internalizing behavior were stronger for younger children. The indirect effect of low collective efficacy on behavior problems through corporal punishment was not significant. These findings highlight the importance of multilevel interventions that promote both neighborhood collective efficacy and non-physical discipline in early childhood.

**Grogan-Kaylor, A., Galano, M., Howell, K.H., Miller-Graff, L., Graham-Bermann, S.A., (2016). Reductions in Parental Use of Corporal Punishment on Pre-School Children following Participation in the Moms' Empowerment Program. *Journal of Interpersonal Violence*.**

Corporal punishment is a widely used, and widely endorsed form of parental discipline. Inter-partner violence places enormous stress upon women. The rate of corporal punishment is higher in homes where other types of domestic violence are also occurring. This study compares two groups: those who participated in an intervention for women exposed to IPV (The Moms' Empowerment Program), and those in a comparison group. Using standardized measures, women in both groups were assessed at baseline and at the end of the program, five weeks later.  The 113 mothers who participated in the MEP program had significantly improved their parenting, such that they had less use of physical punishment post-intervention. Findings suggest that a relatively brief community-based intervention program can reduce the use of parental physical punishment even in disadvantaged populations coping with stressful circumstances.

**Ma, J., Grogan-Kaylor, A., Delva, J. (2016). Behavior Problems Among Youth Exposed to Family and Community Violence in Chile. *Family Relations*, [http://dx.doi.org/10.1111/fare.12199](http://dx.doi.org/10.1111/fare.12199).**

Research that simultaneously examines the relationship of multiple types of family andcommunity violence with youth outcomes is limited in the previous research literature, particularly in Latin America. This study examined the relationship of youth exposure to familyand community violence—parental use of corporal punishment, violence in the community,intimate partner physical aggression—with eight subscales of the Youth Self Report among a Chilean sample of 593 youth-mother pairs. Results from multilevel models indicated a positive association between youth exposure to violence in the family and community, and a wide range of behavior problem outcomes, in particular, aggression. With growing evidence concerning the detrimental effect of violence on youth’s well-being, these findings highlight the need for a more comprehensive understanding of the various kinds of violence youth are exposed to within thefamily and community and the concomitant need to reduce multiple forms of violence.

<p id="meta-analysis">**Gershoff, E. T., &amp; Grogan-Kaylor, A. (2016). Spanking and Child Outcomes: Old Controversies and New Meta-Analyses. *Journal of Family Psychology*,  [http://dx.doi.org/10.1037/fam0000191](http://dx.doi.org/10.1037/fam0000191)** 

> This article received a [considerable amount of media attention](media-mentions-CP-meta.html).

> We discuss some of the implications of research on spanking--including our meta-analysis--[here](http://theconversation.com/hard-evidence-spanking-could-lead-to-health-problems-antisocial-behavior-58566).

> [Joan Lipuscek](http://www.joanlipuscek.com/child-therapy-news/new-research-in-the-old-spanking-debate) has written a really nice blog post thinking through some of the issues raised by our research.

Whether spanking is helpful or harmful to children continues to be the source of considerable debateamong both researchers and the public. This article addresses 2 persistent issues, namely whether effect sizes for spanking are distinct from those for physical abuse, and whether effect sizes for spanking arerobust to study design differences. Meta-analyses focused specifically on spanking were conducted on atotal of 111 unique effect sizes representing 160,927 children. Thirteen of 17 mean effect sizes weresignificantly different from zero and all indicated a link between spanking and increased risk fordetrimental child outcomes. Effect sizes did not substantially differ between spanking and physical abuseor by study design characteristics.

**Gershoff and Grogan-Kaylor, (2016). Race as a Moderator of Associations between Spanking and Child Outcomes. Family Relations, 65, 490-501, [http://dx.doi.org/h10.1111/fare.12205](http://dx.doi.org/h10.1111/fare.12205)**

The cultural normativeness perspective arguesthat parenting practices such as spanking aremore beneficial for children when they occur incultural groups within which they are normative. Research on this issue in the United Stateshas focused on race as a marker of culture,and findings have been mixed. The presentstudy presents meta-analyses of five studiesthat reported effect sizes separately for White(n= 11,814) and Black (n= 3,065) Americanchildren (5 to 14 years of age). Mean weightedeffect sizes for both groups indicated statisticallysignificant associations with detrimentaloutcomes; they were not statistically significantlydifferent from one another. Contrary tothe cultural normativeness perspective, theseresults demonstrate that spanking is similarlyassociated with detrimental outcomes for White and Black children in the United States.

**Lee, S. J., Grogan-Kaylor, A., & Berger, L. M. (2014). Parental spanking of 1-year-old children and subsequent child protective services involvement. *Child Abuse and Neglect*.**

The majority of U.S. parents spank their children, often beginning when their children are very young. We examined families (<i>N</i>=2,788) who participated in a longitudinal community-based study of new births in urban areas. Prospective analyses examined whether spanking by the child's mother, father, or mother's current partner when the child was 1-year-old was associated with household CPS involvement between age 1 and age 5. Results indicated that 30% of 1-year-olds were spanked at least once in the past month. Spanking at age 1 was associated with increased odds of subsequent CPS involvement (adjusted odds ratio=1.36, 95% CI [1.08, 1.71],<i>p</i>&lt;.01). When compared to non-spanked children, there was a 33% greater probability of subsequent CPS involvement for children who were spanked at age 1. Given the undesirable consequences of spanking children and a lack of empirical evidence to suggest positive effects of physical punishment, professionals who work with families should counsel parents not to spank infants and toddlers. For optimal benefits, efforts to educate parents regarding alternative forms of discipline should begin during the child's first year of life.

**Han, Y. and Grogan-Kaylor, A. (2013). Parenting and Youth Psychosocial Well-Being in South Korea Using Fixed Effects Models. *Journal of Family Issues*, 34(5), 689-715.**

The present study analyzed the relationship between various parenting practices and an array of adolescent psychosocial outcomes in South Korea, while controlling for demographic, family, school, and neighborhood factors. Analyses were based on five waves of the nationally representative Korea Youth Panel Survey using 3,263 youth (Person Years = 13,121). All parenting (warmth, monitoring, and hostility) and youth’s psychosocial (confidence, depressive symptoms, and aggressive behaviors) measures were reported by the youth. Within-person fixed-effects regression results indicated that parental warmth not only facilitated youth’s confidence, but also protected them against feelings of depression and aggression. Parental monitoring was a predictor of positive self-perception. As a parental measure with a preventive-orientation, monitoring exhibited a trend toward reducing aggressive behavior. On the other hand, hostile parenting was significantly associated with depressive symptoms andaggressive behaviors. Factors external to the family, such as school and neighborhoods were also associated with mental health outcomes among Korean youth.

**Ma, J., Han, Y., Grogan-Kaylor, A., Delva, J., &amp; Castillo, M. (2012). Corporal punishment and youth externalizing behavior in Santiago, Chile. *Child Abuse and Neglect*.**

Objectives: Corporal punishment is still widely practiced around the globe, despite the large body of child development research that substantiates its short- and long-term consequences. Within this context, this paper examined the relationship between parental use of corporal punishment and youth externalizing behavior with a Chilean sample to add to the growing empirical evidence concerning the potential relationship between increased corporal punishment and undesirable youth outcomes across cultures.

Methods: Analysis was based on 919 adolescents in Santiago, Chile. Descriptive and multivariate analyses were conducted to examine the extent to which parents’ use of corporal punishment and positive family measures were associated with youth externalizing behavior. Furthermore, the associations between self-reported externalizing behavior and infrequent, as well as frequent, use of corporal punishment were investigated to contribute to understanding how varying levels of parental use of corporal punishment were differently related to youth outcomes.

Results:Both mother’s and father’s use of corporal punishment were associated with greater youth externalizing behavior. Additionally, increases in positive parenting practices, such as parental warmth and family involvement, were met with decreases in youth externalizing behavior when controlling for youth demographics, family socioeconomic status, and parents’ use of corporal punishment. Finally, both infrequent and frequent use of corporal punishment were positively associated with higher youth problem behaviors, though frequent corporal punishment had a stronger relationship with externalizing behavior than did infrequent corporal punishment.

Conclusions: Parental use of corporal punishment, even on an occasional basis, is associated with greater externalizing behavior for youth while a warm and involving family environment may protect youth from serious problem behaviors. Therefore, findings of this study add to the growing evidence concerning the negative consequences of corporal punishment for youth outcomes.

**Gershoff, E. T., Grogan-Kaylor, A., Lansford, J. E., Chang, L., Dodge, K. A., Zelli, A., et al. (2010). Parent discipline practices in an international sample: Associations with child behaviors and moderation by perceived normativeness. *Child Development*, 81(2), 480-495.**

This study examined the associations of 11 discipline techniques with children’s aggressive and anxious behaviors in an international sample of mothers and children from 6 countries and determined whether any significant associations were moderated by mothers’ and children’s perceived normativeness of the techniques. Participants included 292 mothers and their 8- to 12-year-old children living in China, India, Italy, Kenya, Philippines, and Thailand. Parallel multilevel and fixed effects models revealed that mothers’ use of corporal punishment, expressing disappointment, and yelling were significantly related to more child aggression symptoms, whereas giving a time-out, using corporal punishment, expressing disappointment, and shaming were significantly related to greater child anxiety symptoms. Some moderation of these associations was found for children’s perceptions of normativeness.

**Grogan-Kaylor, A., &amp; Otis, M. (2007). Predictors of corporal punishment: a tobit analysis. *Family Relations*, 56(1), 80-91.**

Corporal punishment has been the focus of considerable study over the past decade. Some recent research suggesting that the use of corporal punishment may have significant long-term negative effects on children has prompted increasing exploration and interest in the issue. We utilized tobit regression analysis and data from the 2000 National Longitudinal Study of Youth to examine both the prevalence and chronicity of spanking in a nationally representative sample of parents. Mother’s characteristics (e.g., age, education) and neighborhood context did not show a relationship with parental use of corporal punishment. Among parents who used corporal punishment, being Protestant had a relatively large relationship with its use. Although children’s externalizing behaviors had some association with parent’s propensity to spank, findings suggest that use of corporal punishment may be better understood as part of a constellation of behaviors relating to a parenting style. Further, findings indicate that it is easier to predict the incidence of corporal punishment than it is to predict frequency of use.

**Grogan-Kaylor, A. (2005). Corporal Punishment and the Growth Trajectory of Children’s Antisocial Behavior. *Child Maltreatment*, 10(3), 283-292.**

Despite considerable research, the relationship between corporal punishment and antisocial behavior is unclear. This analysis examined: (a) the functional form of this relationship (b) the correlation of initial antisocial behavior and changes in antisocial behavior (c) differences in the relationship of corporal punishment and antisocial behavior by race (d) whether this relationship could be accounted for by unmeasured characteristics of children and their families. Data from 6,912 children in the National Longitudinal Survey of Youth were analyzed using hierarchical linear models. Findings suggested that corporal punishment has a relationship with children’s initial antisocial behavior and with changes in antisocial behavior. No evidence was found for differences in the effect of corporal punishment across racial groups. The relationship between corporal punishment and antisocial behavior persists even when accounting for unmeasured time invariant characteristics of children and families. The findings suggest that corporal punishment is not a preferable technique for disciplining children.

**Grogan-Kaylor, A. (2005). Relationship of Corporal Punishment and Antisocial Behavior by Neighborhood, *Archives Of Pediatric and Adolescent Medicine*, 159(10), 938-942. [http://dx.doi.org/10.1001/archpedi.159.10.938](http://dx.doi.org/10.1001/archpedi.159.10.938)**

Objective: To examine the relationship of corporal punishment with children’s behavior problems while accounting for neighborhood context, and while using stronger statistical methods than previous literature in this area. To examine whether different levels of corporal punishment have different effects in different neighborhood contexts.

Design: Longitudinal cohort study

Setting: General Community

Participants: 1,943 mother child pairs from the National Longitudinal Survey of Youth

Main Outcome Measure(s):Internalizing and Externalizing Behavior Problem Scales of the Behavior Problems Index

Results, and Conclusions: Parental use of corporal punishment was associated with a .71 increase (p&lt;.05) in children’s externalizing behavior problems even when several parenting behaviors, neighborhood quality, and all time invariant variables were accounted for. The association of corporal punishment and children’s externalizing behavior problems was not dependent on neighborhood context. The research found no discernible relationship between corporal punishment and internalizing behavior problems.

**Grogan-Kaylor, A. (2004). The Effect Of Corporal Punishment On Antisocial Behavior In Children. *Social Work Research*, 28(3), 153-164.**

Objective: This study had three aims: to examine the effect of corporal punishment on antisocial behavior of children using stronger statistical controls than the previous literature in this area; to examine whether the effect of corporal punishment on antisocial behavior is nonlinear; and to investigate whether or not the effects of corporal punishment on antisocial behavior differ across racial and ethnic groups.

Method: The study used a non-experimental design and data from the National Longitudinal Survey of Youth. The analysis was conducted using fixed effects methods to control for observed independent variables as well as all unobserved time invariant variables. Dummy variables were constructed for corporal punishment to allow for potential nonlinear effects. Interaction terms of corporal punishment and racial or ethnic group were constructed to test for the possibility of differing effects of corporal punishment on antisocial behavior across racial and ethnic groups.

Results: Corporal punishment has a nontrivial effect on children’s antisocial behavior in later years despite the strong controls introduced by the fixed effects models. Both lower and higher levels of corporal punishment appear to have this effect. The analysis provides no evidence for differences in the effect of corporal punishment across racial and ethnic groups.

Conclusions: This study provides further and methodologically rigorous support for the growing literature that suggests that the use of corporal punishment is associated with an increase in children’s antisocial behavior.
