---
title: "Media Mentions of Meta-Analysis of Research on Corporal Punishment"
author: "Andy Grogan-Kaylor" 
date: "today"
format: 
  html:
    theme: cosmo
    toc: false
    number-sections: false
    css: styles.css
---

```{r}
#| column: page
#| fig-height: 4
#| echo: false
#| message: false

library(readxl)

CP_Meta_Summary_Results <- read_excel("data/CP Meta Summary Results.xlsx")

library(ggplot2)

library(plotly)

p1 <- ggplot(CP_Meta_Summary_Results,
             aes(x = reorder(Outcome, d),
                 y = d,
                 label = Outcome,
                 fill = d)) + 
  geom_bar(stat = "identity") +
  scale_fill_viridis_c() +
  coord_flip() +
  labs(title= "Effect Sizes of Physical Punishment",
       x = "Outcome",
       y = "Cohen's d Effect Size",
       caption = "Gershoff and Grogan-Kaylor, 2016") +
  theme(legend.position = "none",
        title = element_text(size = rel(.5)),
        axis.text = element_text(size = rel(.75)))

ggplotly(p1, tooltip = c("fill", "label"))

```

Media Mentions of Meta-Analysis of Corporal Punishment Research:

> Gershoff, E. T., & Grogan-Kaylor, A. (2016). Spanking and Child Outcomes: Old Controversies and New Meta-Analyses. Journal of Family Psychology. 30(4), 453-469. [http://dx.doi.org/10.1037/fam0000191](http://dx.doi.org/10.1037/fam0000191) 

Our meta-analysis of 50 years of research on corporal punishment received at least 100 mentions in the English language news media.  Further, a report from University of Michigan News indicated that the press release from UM News received "more than 100 hits in Spanish, 60 in Chinese, 43 in Portuguese and 23 in India."

Here are some of the many mentions:

* mentioned in the *CNN* article "[These are the countries where spanking is illegal](https://www.cnn.com/2018/03/12/health/spanking-laws-parenting-without-borders-intl/index.html)"

* featured in *The Telegraph* article, "[Why you should never spank a child - major research project confirms dangers](https://www.telegraph.co.uk/science/2016/04/26/why-you-should-never-spank-a-child---major-research-project-conf/)"

* featured in *The Boston Globe* article, "[Spanking your kid is about as harmful as child abuse, says study](https://www.bostonglobe.com/lifestyle/2016/04/27/study-spanking-nearly-detrimental-abuse/X44bY3WymbVSv9LSRrKLWL/story.html)"

* featured in the *Good Morning America* segment, "[New Report Says Spanking May Be Linked to Lifelong Social, Mental Health Problems in Kids](https://abcnews.go.com/GMA/video/study-spanking-linked-lifelong-social-mental-health-problems-38723342)"

*	featured in *The Atlantic* article, "[The Strong Evidence Against Spanking](https://www.theatlantic.com/health/archive/2016/04/the-strong-evidence-against-spanking/479937/)"

*	featured in the *Telemundo* article, "[Estudio: Nalgadas no son buenas para disciplinar](https://www.telemundo47.com/noticias/salud/estudio-afirma-que-nalgadas-no-son-buena-opcion-para-disciplinar-universidad-michigan-universidad-de-texas-377262761.html)"

*	featured in the *U.S. News & World Report* article, "[Don't Spank Your Kids, Says 50 Years of Research](https://www.usnews.com/news/articles/2016-04-26/spanking-kids-causes-mental-health-issues-study-shows)"

*	featured in the *CNN en Español* article, "[Por que nunca deberías castigar a tus hijos dándoles palmadas](https://cnnespanol.cnn.com/2016/04/26/por-que-nunca-deberias-castigar-a-tus-hijos-dandoles-palmadas/#0)"

*	cited in the *Le Monde* article, “[La France est-elle prête à interdire la fessée?](https://www.lemonde.fr/societe/article/2016/04/30/la-france-est-elle-prete-a-interdire-la-fessee_4911258_3224.html)”

*	cited in the *Vox* article, “[Parents have been spanking children for millennia. 50 years of scientific evidence says they were wrong](https://www.vox.com/2016/4/27/11510118/spanking-children)”

We discuss some of the implications of research on spanking--including our meta-analysis--[in an article](http://theconversation.com/hard-evidence-spanking-could-lead-to-health-problems-antisocial-behavior-58566) for *The Conversation*.

Joan Lipuscek has written a [really nice blog post thinking through some of the issues raised by our research](http://www.joanlipuscek.com/child-therapy-news/new-research-in-the-old-spanking-debate).

Original press releases

* University of Michigan: 

     - [Spanking Does More Harm Than Good](http://ns.umich.edu/new/releases/23732-spanking-does-more-harm-than-good)
     - [Disciplinar con nalgadas perjudica a los niños](http://espanol.umich.edu/noticias/comunicados-de-prensa/2016/04/25/disciplinar-con-nalgadas-dana-a-los-ninos/)
     
* University of Texas: [Risks of Harm From Spanking Confirmed by Researchers](http://news.utexas.edu/2016/04/25/risks-of-harm-from-spanking-confirmed-by-researchers)



